<a href="https://colab.research.google.com/github/random3770/exploratory-data-analysis/blob/main/experiment_5(4-8-26).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Discretization and binning:

In [17]:
data_for_cut = fraud_test_df['amt']
import pandas as pd
bins = [0, 50, 200, 1000, data_for_cut.max() + 1]
category = pd.cut(data_for_cut, bins)
print(category)

0           (0.0, 50.0]
1           (0.0, 50.0]
2           (0.0, 50.0]
3         (50.0, 200.0]
4           (0.0, 50.0]
              ...
555714      (0.0, 50.0]
555715    (50.0, 200.0]
555716    (50.0, 200.0]
555717      (0.0, 50.0]
555718      (0.0, 50.0]
Name: amt, Length: 555719, dtype: category
Categories (4, interval[float64, right]): [(0.0, 50.0] < (50.0, 200.0] < (200.0, 1000.0] <
                                           (1000.0, 22769.11]]

In [18]:
print(pd.Series(category).value_counts())

amt
(0.0, 50.0]           288930
(50.0, 200.0]         241440
(200.0, 1000.0]        23766
(1000.0, 22769.11]      1583
Name: count, dtype: int64

In [19]:
bin_names = ['Small Amount', 'Medium Amount', 'Large Amount', 'Very Large Amount']
print(pd.cut(data_for_cut, bins, labels=bin_names))

0          Small Amount
1          Small Amount
2          Small Amount
3         Medium Amount
4          Small Amount
              ...
555714     Small Amount
555715    Medium Amount
555716    Medium Amount
555717     Small Amount
555718     Small Amount
Name: amt, Length: 555719, dtype: category
Categories (4, object): ['Small Amount' < 'Medium Amount' < 'Large Amount' < 'Very Large Amount']

In [20]:
import numpy as np

data_for_equal_bins = fraud_test_df['city_pop']
print(pd.cut(data_for_equal_bins, 5, precision=0))

0         (-2884.0, 581358.0]
1         (-2884.0, 581358.0]
2         (-2884.0, 581358.0]
3         (-2884.0, 581358.0]
4         (-2884.0, 581358.0]
                 ...
555714    (-2884.0, 581358.0]
555715    (-2884.0, 581358.0]
555716    (-2884.0, 581358.0]
555717    (-2884.0, 581358.0]
555718    (-2884.0, 581358.0]
Name: city_pop, Length: 555719, dtype: category
Categories (5, interval[float64, right]): [(-2884.0, 581358.0] < (581358.0, 1162694.0] <
                                           (1162694.0, 1744029.0] < (1744029.0, 2325365.0] <
                                           (2325365.0, 2906700.0]]

In [21]:
data_for_qcut = f_train_df['amt']
category3 = pd.qcut(data_for_qcut, 4)
print(category3)

0             (0.999, 9.65]
1          (83.14, 28948.9]
2          (83.14, 28948.9]
3             (9.65, 47.52]
4             (9.65, 47.52]
                 ...
1296670       (9.65, 47.52]
1296671      (47.52, 83.14]
1296672    (83.14, 28948.9]
1296673      (47.52, 83.14]
1296674       (0.999, 9.65]
Name: amt, Length: 1296675, dtype: category
Categories (4, interval[float64, right]): [(0.999, 9.65] < (9.65, 47.52] < (47.52, 83.14] <
                                           (83.14, 28948.9]]

In [22]:
print(pd.Series(category3).value_counts())

amt
(0.999, 9.65]       324325
(47.52, 83.14]      324151
(83.14, 28948.9]    324112
(9.65, 47.52]       324087
Name: count, dtype: int64

In [16]:
fraud_test_df = pd.read_csv('/content/fraudTest.csv')
f_train_df = pd.read_csv('/content/fraudTrain.csv')

print("Fraud Test DataFrame Info:")
fraud_test_df.info()
print("\nFraud Train DataFrame Info:")
f_train_df.info()

print("\nFraud Test DataFrame Head:")
display(fraud_test_df.head())
print("\nFraud Train DataFrame Head:")
display(f_train_df.head())

Fraud Test DataFrame Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 555719 entries, 0 to 555718
Data columns (total 23 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   Unnamed: 0             555719 non-null  int64
 1   trans_date_trans_time  555719 non-null  object
 2   cc_num                 555719 non-null  int64
 3   merchant               555719 non-null  object
 4   category               555719 non-null  object
 5   amt                    555719 non-null  float64
 6   first                  555719 non-null  object
 7   last                   555719 non-null  object
 8   gender                 555719 non-null  object
 9   street                 555719 non-null  object
 10  city                   555719 non-null  object
 11  state                  555719 non-null  object
 12  zip                    555719 non-null  int64
 13  lat                    555719 non-null  float64
 14  long                   555719 non-null  float64
 15  city_pop               555719 non-null  int64
 16  job                    555719 non-null  object
 17  dob                    555719 non-null  object
 18  trans_num              555719 non-null  object
 19  unix_time              555719 non-null  int64
 20  merch_lat              555719 non-null  float64
 21  merch_long             555719 non-null  float64
 22  is_fraud               555719 non-null  int64
dtypes: float64(5), int64(6), object(12)
memory usage: 97.5+ MB

Fraud Train DataFrame Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1296675 entries, 0 to 1296674
Data columns (total 23 columns):
 #   Column                 Non-Null Count    Dtype
---  ------                 --------------    -----
 0   Unnamed: 0             1296675 non-null  int64
 1   trans_date_trans_time  1296675 non-null  object
 2   cc_num                 1296675 non-null  int64
 3   merchant               1296675 non-null  object
 4   category               1296675 non-null  object
 5   amt                    1296675 non-null  float64
 6   first                  1296675 non-null  object
 7   last                   1296675 non-null  object
 8   gender                 1296675 non-null  object
 9   street                 1296675 non-null  object
 10  city                   1296675 non-null  object
 11  state                  1296675 non-null  object
 12  zip                    1296675 non-null  int64
 13  lat                    1296675 non-null  float64
 14  long                   1296675 non-null  float64
 15  city_pop               1296675 non-null  int64
 16  job                    1296675 non-null  object
 17  dob                    1296675 non-null  object
 18  trans_num              1296675 non-null  object
 19  unix_time              1296675 non-null  int64
 20  merch_lat              1296675 non-null  float64
 21  merch_long             1296675 non-null  float64
 22  is_fraud               1296675 non-null  int64
dtypes: float64(5), int64(6), object(12)
memory usage: 227.5+ MB

Fraud Test DataFrame Head:

,Unnamed: 0,trans_date_trans_time,cc_num,merchant,category,amt,first,last,gender,street,...,lat,long,city_pop,job,dob,trans_num,unix_time,merch_lat,merch_long,is_fraud
0,0,2020-06-21 12:14:25,2291163933867244,fraud_Kirlin and Sons,personal_care,2.86,Jeff,Elliott,M,351 Darlene Green,...,33.9659,-80.9355,333497,Mechanical engineer,1968-03-19,2da90c7d74bd46a0caf3777415b3ebd3,1371816865,33.986391,-81.200714,0
1,1,2020-06-21 12:14:33,3573030041201292,fraud_Sporer-Keebler,personal_care,29.84,Joanne,Williams,F,3638 Marsh Union,...,40.3207,-110.4360,302,"Sales professional, IT",1990-01-17,324cc204407e99f51b0d6ca0055005e7,1371816873,39.450498,-109.960431,0
2,2,2020-06-21 12:14:53,3598215285024754,"fraud_Swaniawski, Nitzsche and Welch",health_fitness,41.28,Ashley,Lopez,F,9333 Valentine Point,...,40.6729,-73.5365,34496,"Librarian, public",1970-10-21,c81755dbbbea9d5c77f094348a7579be,1371816893,40.495810,-74.196111,0
3,3,2020-06-21 12:15:15,3591919803438423,fraud_Haley Group,misc_pos,60.05,Brian,Williams,M,32941 Krystal Mill Apt. 552,...,28.5697,-80.8191,54767,Set designer,1987-07-25,2159175b9efe66dc301f149d3d5abf8c,1371816915,28.812398,-80.883061,0
4,4,2020-06-21 12:15:17,3526826139003047,fraud_Johnston-Casper,travel,3.19,Nathan,Massey,M,5783 Evan Roads Apt. 465,...,44.2529,-85.0170,1126,Furniture designer,1955-07-06,57ff021bd3f328f8738bb535c302a31b,1371816917,44.959148,-85.884734,0

Fraud Train DataFrame Head:

,Unnamed: 0,trans_date_trans_time,cc_num,merchant,category,amt,first,last,gender,street,...,lat,long,city_pop,job,dob,trans_num,unix_time,merch_lat,merch_long,is_fraud
0,0,2019-01-01 00:00:18,2703186189652095,"fraud_Rippin, Kub and Mann",misc_net,4.97,Jennifer,Banks,F,561 Perry Cove,...,36.0788,-81.1781,3495,"Psychologist, counselling",1988-03-09,0b242abb623afc578575680df30655b9,1325376018,36.011293,-82.048315,0
1,1,2019-01-01 00:00:44,630423337322,"fraud_Heller, Gutmann and Zieme",grocery_pos,107.23,Stephanie,Gill,F,43039 Riley Greens Suite 393,...,48.8878,-118.2105,149,Special educational needs teacher,1978-06-21,1f76529f8574734946361c461b024d99,1325376044,49.159047,-118.186462,0
2,2,2019-01-01 00:00:51,38859492057661,fraud_Lind-Buckridge,entertainment,220.11,Edward,Sanchez,M,594 White Dale Suite 530,...,42.1808,-112.2620,4154,Nature conservation officer,1962-01-19,a1a22d70485983eac12b5b88dad1cf95,1325376051,43.150704,-112.154481,0
3,3,2019-01-01 00:01:16,3534093764340240,"fraud_Kutch, Hermiston and Farrell",gas_transport,45.00,Jeremy,White,M,9443 Cynthia Court Apt. 038,...,46.2306,-112.1138,1939,Patent attorney,1967-01-12,6b849c168bdad6f867558c3793159a81,1325376076,47.034331,-112.561071,0
4,4,2019-01-01 00:03:06,375534208663984,fraud_Keeling-Crist,misc_pos,41.96,Tyler,Garcia,M,408 Bradley Rest,...,38.4207,-79.4629,99,Dance movement psychotherapist,1986-03-28,a41d7549acf90789359a9aa5346dcb46,1325376186,38.674999,-78.632459,0

## Outlier detection and filtering

In [27]:
import pandas as pd
df = pd.read_csv('https://raw.githubusercontent.com/salemprakash/EDA/main/Data/sales.csv')
display(df.head(10))

,Account,Company,Order,SKU,Country,Year,Quantity,UnitPrice,transactionComplete
0,123456779,Kulas Inc,99985,s9-supercomputer,Aruba,1981,5148,545,False
1,123456784,GitHub,99986,s4-supercomputer,Brazil,2001,3262,383,False
2,123456782,Kulas Inc,99990,s10-supercomputer,Montserrat,1973,9119,407,True
3,123456783,My SQ Man,99999,s1-supercomputer,El Salvador,2015,3097,615,False
4,123456787,ABC Dogma,99996,s6-supercomputer,Poland,1970,3356,91,True
5,123456778,Super Sexy Dingo,99996,s9-supercomputer,Costa Rica,2004,2474,136,True
6,123456783,ABC Dogma,99981,s11-supercomputer,Spain,2006,4081,195,False
7,123456785,ABC Dogma,99998,s9-supercomputer,Belarus,2015,6576,603,False
8,123456778,Loolo INC,99997,s8-supercomputer,Mauritius,1999,2460,36,False
9,123456775,Kulas Inc,99997,s7-supercomputer,French Guiana,2004,1831,664,True

In [29]:
df['TotalPrice'] = df['UnitPrice'] * df['Quantity']
display(df.head())

,Account,Company,Order,SKU,Country,Year,Quantity,UnitPrice,transactionComplete,TotalPrice
0,123456779,Kulas Inc,99985,s9-supercomputer,Aruba,1981,5148,545,False,2805660
1,123456784,GitHub,99986,s4-supercomputer,Brazil,2001,3262,383,False,1249346
2,123456782,Kulas Inc,99990,s10-supercomputer,Montserrat,1973,9119,407,True,3711433
3,123456783,My SQ Man,99999,s1-supercomputer,El Salvador,2015,3097,615,False,1904655
4,123456787,ABC Dogma,99996,s6-supercomputer,Poland,1970,3356,91,True,305396

In [30]:
TotalTransaction = df["TotalPrice"]
display(TotalTransaction[np.abs(TotalTransaction) > 3000000])

2       3711433
7       3965328
13      4758900
15      5189372
17      3989325
         ...
9977    3475824
9984    5251134
9987    5670420
9991    5735513
9996    3018490
Name: TotalPrice, Length: 2094, dtype: int64

In [31]:
display(df[np.abs(TotalTransaction) > 6741112])

,Account,Company,Order,SKU,Country,Year,Quantity,UnitPrice,transactionComplete,TotalPrice
818,123456781,Gen Power,99991,s1-supercomputer,Burkina Faso,1985,9693,696,False,6746328
1402,123456778,Will LLC,99985,s11-supercomputer,Austria,1990,9844,695,True,6841580
2242,123456770,Name IT,99997,s9-supercomputer,Myanmar,1979,9804,692,False,6784368
2876,123456772,Gen Power,99992,s10-supercomputer,Mali,2007,9935,679,False,6745865
3210,123456782,Loolo INC,99991,s8-supercomputer,Kuwait,2006,9886,692,False,6841112
3629,123456779,My SQ Man,99980,s3-supercomputer,Hong Kong,1994,9694,700,False,6785800
7674,123456781,Loolo INC,99989,s6-supercomputer,Sri Lanka,1994,9882,691,False,6828462
8645,123456789,Gen Power,99996,s11-supercomputer,Suriname,2005,9742,699,False,6809658
8684,123456785,Gen Power,99989,s2-supercomputer,Kenya,2013,9805,694,False,6804670

## Feature scaling and normalization:

In [26]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import MinMaxScaler, StandardScaler, RobustScaler

data = {
 'Age': [25, 30, 45, 35, 22],
 'Salary': [50000, 64000, 120000, 85000, 1200000]
}
df = pd.DataFrame(data)
print("Original Data:\n", df, "\n")

min_max_scaler = MinMaxScaler()
df_min_max = pd.DataFrame(
 min_max_scaler.fit_transform(df),
 columns=df.columns
)
print("Min-Max Scaled Data:\n", df_min_max, "\n")

standard_scaler = StandardScaler()
df_standard = pd.DataFrame(
 standard_scaler.fit_transform(df),
 columns=df.columns
)
print("Standardized Data:\n", df_standard, "\n")

Original Data:
    Age   Salary
0   25    50000
1   30    64000
2   45   120000
3   35    85000
4   22  1200000

Min-Max Scaled Data:
         Age    Salary
0  0.130435  0.000000
1  0.347826  0.012174
2  1.000000  0.060870
3  0.565217  0.030435
4  0.000000  1.000000

Standardized Data:
         Age    Salary
0 -0.788742 -0.565609
1 -0.172537 -0.534409
2  1.676077 -0.409609
3  0.443667 -0.487609
4 -1.158465  1.997236